### DISCUSSION TITLE
Getting chatbot-ui-manual to run with Llama.cpp

### DISCUSSION THREAD

**Discussion by jamesbraza** [mudler/LocalAI#1068] [Q&A]
I have:
- Downloaded my Llama.cpp ([TheBloke/Llama-2-13B-chat-GGUF/llama-2-13b-chat.Q4_K_S.gguf](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/tree/main)) model to `models/` and `examples/chatbot-ui-manual/models/`
- Created `examples/chatbot-ui-manual/models/llama-2-13b-chat.Q4_K_S.yaml`:

```yaml
---
name: llama-2-13B-chat
parameters:
  model: llama-2-13b-chat.Q4_K_S
  temperature: 0.3
context_size: 512
threads: 10
backend: llama
```

When I then run `docker-compose up --pull always`, I only see Default model:

![screenshot of Chatbot UI](https://github.com/go-skynet/LocalAI/assets/8990777/222584a6-5df3-4866-be11-9cef6862184c)

What am I missing here/doing wrong?
