### DISCUSSION TITLE
GGUF trouble

### DISCUSSION THREAD

**Discussion by thebrahman** [mudler/LocalAI#1080] [General]
Why wont this model work:
https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/blob/main/llama-2-7b-chat.Q5_K_M.gguf

with this config:
```
backend: llama
context_size: 2000
f16: true ## If you are using cpu set this to false
gpu_layers: 17
batch: 512
name: llama-2-7b
parameters:
  model: llama-2-7b-chat.Q5_K_M.gguf
  temperature: 0.2
  top_k: 40
  top_p: 0.65
roles:
  assistant: 'ASSISTANT:'
  system: 'SYSTEM:'
  user: 'USER:'
template:
  chat: chat
  completion: completion
```

I can run this model from the example on the website:
'luna-ai-llama2-uncensored.ggmlv3.q5_K_M.bin'
with the same config as above but with 'llama-stable'
