### DISCUSSION TITLE
Speech-To-Text not working

### DISCUSSION THREAD

**Discussion by manuelkamp** [mudler/LocalAI#1230] [Q&A] [answered]
I use the whisper-1 for Speech-To-Text, but it is not working. it shows error about missing ffmpeg, but i use it in my docker-compose.yaml:
```
version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:latest-ffmpeg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
      - ./images/:/tmp/generated/images/
    command: ["/usr/bin/local-ai" ]
```

This is the error I am getting:
`curl http://localhost:8080/v1/audio/transcriptions -H "Content-Type: multipart/form-data" -F file="@$PWD/gb1.ogg" -F model="whisper-1"
{"error":{"code":500,"message":"rpc error: code = Unknown desc = error: exit status 127 out: /bin/sh: 1: ffmpeg: not found\n","type":""}}`
