### DISCUSSION TITLE
Sentencetransformers URL

### DISCUSSION THREAD

**Discussion by mforell** [mudler/LocalAI#1369] [Q&A] [answered]
**LocalAI version:**

quay.io/go-skynet/local-ai:master-cublas-cuda11-ffmpeg

**Describe the bug**

Trying to use backend: sentencetransformers. 

The yaml we use:
```yaml
- url: OUR_LINK_TO_THE_GALLERY/base.yaml
  name: text-embedding-all-miniLM-L6
  license: mit
  urls:
    - https://huggingface.co/skeskinen/ggml
  tags:
    - license:mit
    - region:us
  overrides:
    parameters:
        model: all-MiniLM-L12-v2/ggml-model-q4_0.bin
    embeddings: true
    backend: sentencetransformers
  files:
    - filename: all-MiniLM-L6-v2/ggml-model-q4_0.bin
      sha256: ""
      uri: https://huggingface.co/skeskinen/ggml/resolve/main/all-MiniLM-L6-v2/ggml-model-q4_0.bin
```

When we try to access the model, we get the Error `Not Found for url: https://huggingface.co/api/models/all-MiniLM-L12-v2/ggml-model-q4_0.bin.\  ` I t appears that a point is added to the url param and the model cannot be found. 

The generated yaml file looks like:
```yaml
backend: sentencetransformers
context_size: 1024
embeddings: true
name: text-embedding-all-miniLM-L6
parameters:
  model: "all-MiniLM-L12-v2/ggml-model-q4_0.bin"

```
The complete response with the error:
Response: 
```json

{
	"error": {
		"code": 500,
		"message": "could not load model (no success): Unexpected err=RepositoryNotFoundError('401 Client Error. (Request ID: Root=1-6565b896-57b5d77f3f3e5fe4797ea763;3d39a4f7-c62a-42f4-b473-7866a02c0bb2)\\n\\nRepository Not Found for url: https://huggingface.co/api/models/all-MiniLM-L12-v2/ggml-model-q4_0.bin.\\nPlease make sure you specified the correct `repo_id` and `repo_type`.\\nIf you are trying to access a private or gated repo, make sure you are authenticated.\\nInvalid username or password.'), type(err)=<class 'huggingface_hub.utils._errors.RepositoryNotFoundError'>",
		"type": ""
	}
}
```

**To Reproduce**

Use the attached yamls.
**Expected behavior**

The point should not be added to the url param when making a request.
**Logs**

**Additional context**

[a comment by an automated account is not shown]
