### DISCUSSION TITLE
MeetKai Functionary GGUF models - chat template format unknown

### DISCUSSION THREAD

**Discussion by Anto79-ops** [mudler/LocalAI#1641] [Q&A]
**LocalAI version:**

`quay.io/go-skynet/local-ai:master-cublas-cuda12-ffmpeg`

Using the Jan 21,2024 build

**Environment, CPU architecture, OS, and Version:**

Docker Ubuntu, AMD, 4060 dual GPU

I cannot run the gguf model using standard chat templates

When use the standard chat and chat-block tmpls as shown [here](https://io.midori-ai.xyz/howtos/easy-model/), this error results for a querry

```
anto@ubuntu-cyberpc:~/MyAI/Auto79_Localai/docker/models$ curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "functionary7bq8",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9
   }'
{"created":1705952676,"object":"chat.completion","id":"3b96e0cd-646d-4a40-b689-0b6f891fa638","model":"functionary7bq8","choices":[{"index":0,"finish_reason":"stop","message":{"role":"assistant","content":""}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
```

The devs over at MeetKai say [here](https://github.com/MeetKai/functionary/issues/102) that this model uses a jinja template in tokenizer_config.json:

https://huggingface.co/meetkai/functionary-medium-v2.2/blob/main/tokenizer_config.json#L69

and it would have to be converted to the format of LocalAI

any suggestions how to do this conversion? thanks

**Comment by Anto79-ops** [comment]
anybody have an idea about this? thanks

**Comment by Zen3515** [comment]
## Sources
- https://huggingface.co/meetkai/functionary-small-v2.5/blob/main/tokenizer/tokenizer_config.json
- https://localai.io/advanced/#prompt-templates
- https://github.com/MeetKai/functionary/blob/main/tests/prompt_test_v2.llama3.txt

```jinja2
{% set loop_messages = messages %}
{% for message in loop_messages %}
{%   set content = '' + message['role'] + '\n\n'+ message['content'] | trim + '' %}
{%   if loop.index0 == 0 %}
{%     set content = bos_token + content %}
{%   endif %}
{{ content }}
{% endfor %}
{% if add_generation_prompt %}
{{ 'assistant\n\n' }}
{% endif %}
```

## What I got so far

```yaml
roles:
  user: "user"
  assistant: "assistant"
  system: "system"
  tool: "tool"
template:
  chat_message: |
    <|begin_of_text|>{{.RoleName}}


    {{if .Content}}{{.Content}}{{end}}<|end_of_text|>
  chat: |
    <|begin_of_text|>{{.RoleName}}


    {{if .Content}}{{.Content}}{{end}}assistant
    
    <|end_of_text|>
  completion: |
    {{.Input}}
```

IMHO, it may be better to just run them and use the code (`apply_chat_template`) to convert as shown in https://huggingface.co/meetkai/functionary-small-v2.5#prompt-template
