### DISCUSSION TITLE
Issue with codellama-7b-gguf using docker image cpu only

### DISCUSSION THREAD

**Discussion by t0k4rt** [mudler/LocalAI#1663] [Q&A]
Dear community,
I want to test localai on my local server using docker compose:

```
version: '3'
services:
  localai:
    image: localai/localai:v2.7.0-ffmpeg-core
    ports:
      - 8000:8080
    command: ["codellama-7b-gguf"]
```

The container starts correctly and download the models. 
But when I tried the given example (in the logs):

```
curl http://myserver:8000/v1/completions -H "Content-Type: application/json" -d '{
    "model": "codellama-7b-gguf",
    "prompt": "import socket\n\ndef ping_exponential_backoff(host: str):"
}'
```

I get no  answer from he server with the given logs on the container:

```
localai_1          | 3:21PM INF Loading model '232692e1614183192beee756c58afefc' with backend transformers
localai_1          | 3:22PM ERR Failed starting/connecting to the gRPC service: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:34699: connect: connection refused"
```

The model is supposed to work on cpu only, and my server has 32gb of ram and 4 cores. 
Thanks for your guidance.
