### DISCUSSION TITLE
Cannot get GPU to work

### DISCUSSION THREAD

**Discussion by ape-nq** [mudler/LocalAI#1944] [Q&A]
I've tried `v2.11.0-cublas-cuda12` and compiling current main branch with Mistral.

When doing chat completion log says that layers are offloaded to GPU:
```
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr ggml_cuda_init: found 1 CUDA devices:
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr   Device 0: NVIDIA GeForce RTX 4080, compute capability 8.9, VMM: yes
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr llm_load_tensors: ggml ctx size =    0.22 MiB
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr llm_load_tensors: offloading 5 repeating layers to GPU
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr llm_load_tensors: offloaded 5/33 layers to GPU
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr llm_load_tensors:        CPU buffer size =  5666.11 MiB
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr llm_load_tensors:      CUDA0 buffer size =   853.28 MiB
```

But I get error messages from `llama.cpp`:
```
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr ggml_cuda_compute_forward: ADD failed
 GRPC(mistral-7b-openorca.Q6_K.gguf-127.0.0.1:32909): stderr GGML_ASSERT: /root/LocalAI/backend/cpp/llama/llama.cpp/ggml-cuda.cu:2392: false
```

Also I'm seeing weird values that look like pointers (e.g. `TopP`, `TopK`, `Temperature`) in the config in debug log:
```
Configuration read: &{PredictionOptions:{Model:mistral-7b-openorca.Q6_K.gguf Language: N:0 TopP:0xc0006f7d38 TopK:0xc0006f7d30 Temperature:0xc0006
f7d10 Maxtokens:0xc0006f7dc0 Echo:false Batch:0 IgnoreEOS:false RepeatPenalty:0 Keep:0 FrequencyPenalty:0 PresencePenalty:0 TFZ:0 TypicalP:0 Seed:0xc0006f7df0 NegativePrompt: RopeFreq
Base:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:mistral F16:0xc0006f7cf8 Threads:0xc0006f7d88 Debug:0xc00047d838 Roles:map[] Embeddings
:false Backend:llama-cpp 
``` 

My `mistral.yaml`:
```
backend: llama-cpp
context_size: 4096
f16: true
gpu_layers: 5
mmap: true
name: mistral
parameters:
  model: mistral-7b-openorca.Q6_K.gguf
  temperature: 0.2
  top_k: 40
  top_p: 0.95
stopwords:
- <|im_end|>
template:
  chat: chatml-block
  chat_message: chatml
  completion: completion
threads: 4
```

Any ideas, what I'm doing wrong?
