### DISCUSSION TITLE
Unable to change port exposed

### DISCUSSION THREAD

**Discussion by ralyodio** [mudler/LocalAI#338] [Q&A]
I can't use port 8080. How do I change it?

**Comment by mudler** [comment]
you can set `ADDRESS` or -`-address`. For example, to bind to all addresses on 9090 specify `ADDRESS=:9090` or `--address :9090`

**Reply by ralyodio** [reply]
Is that the exposed port or the internal port

**Comment by ralyodio** [comment]
I get this error:

```
$ docker stack deploy -c docker-compose.yaml tuzafa
1 error(s) decoding:

* error decoding 'Ports': No port specified: :<empty>
```

**Comment by ralyodio** [comment]
So the .env isnt' being picked here:

```
version: '3.6'

services:
  localai:
    image: quay.io/go-skynet/local-ai:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]
    networks:
      - tuzafa

networks:
  tuzafa:
```

.env:

```
PORT=9320
## Set number of threads.
## Note: prefer the number of physical cores. Overbooking the CPU degrades performance notably.
# THREADS=14

## Specify a different bind address (defaults to ":8080")
ADDRESS=:9320
```
