### ISSUE TITLE
Mac Metal : doc example still run in CPU

### ISSUE THREAD

**Issue by jochy** [mudler/LocalAI#1064]
**LocalAI version:**
Last commit on master (8ccf5b2044d13d5668075b2bba4d44ae1fdde06d)

**Environment, CPU architecture, OS, and Version:**
Macbook M2 Max, 64Go Memory, Sonoma beta 7

**Describe the bug**
I have followed the documentation to build and run LocalAi with metal support. However, the example in the documentation still runs on the CPU.

**To Reproduce**
Follow the documentation : https://localai.io/basics/build/#build-on-mac 
See that the CPU is used, not the GPU.

**Expected behavior**
GPU should be used

**Comment by Aisuko** [comment]
Hi, @jochy thanks for your feedback.  You are right, we should add `metal` as a default build type for M1 and M2.

**Comment by jochy** [comment]
Hey @Aisuko , I have tried to build it locally using the `BUILD_TYPE=metal` flag but it failed due to some compilation issues.  I don't know if it's related to my local environment or if it's not working for everyone. 

One thing that could help is to have a Github Action workflow which compiles the code using the `BUILD_TYPE=metal` flag.

**Comment by Aisuko** [comment]
HI @jochy The CPU already in using?

**Comment by mozg31337** [comment]
Hello Guys. 
I am using LocalAI on MacBookPro M1 64gb (yesterdays' git pull). I've built using instructions for the M1/M2 build and it successfully compiled using BUILD_TYPE=metal . However, when i run models i still see the CPU usage and not the GPU. I've used the following model files:

**llama-2-13b-chat.Q4_0.yaml**
name: llama-2-13b-chat.Q4_0
parameters:
  model: llama-2-13b-chat.Q4_0
  gpu_layers: 24
  f16: true
context_size: 4096
model_type: llama

(tried setting gpu_layers: 1 as per documentation and there is no difference)

**llama-2-13b-chat.Q4_0.tmpl**
{{if eq .RoleName "assistant"}}{{.Content}}{{else}}
[INST]
{{if .SystemPrompt}}{{.SystemPrompt}}{{else if eq .RoleName "system"}}<<SYS>>{{.Content}}<</SYS>>

{{else if .Content}}{{.Content}}{{end}}
[/INST]
{{end}}%                           


When i use this model from the text-generation-webui for example, I can see the GPU is being fully utilised. Please let me know what I am doing wrong? Cheers

**Comment by mozg31337** [comment]
> Hello Guys. I am using LocalAI on MacBookPro M1 64gb (yesterdays' git pull). I've built using instructions for the M1/M2 build and it successfully compiled using BUILD_TYPE=metal . However, when i run models i still see the CPU usage and not the GPU. I've used the following model files:
> 
> **llama-2-13b-chat.Q4_0.yaml** name: llama-2-13b-chat.Q4_0 parameters: model: llama-2-13b-chat.Q4_0 gpu_layers: 24 f16: true context_size: 4096 model_type: llama
> 
> (tried setting gpu_layers: 1 as per documentation and there is no difference)
> 
> **llama-2-13b-chat.Q4_0.tmpl** {{if eq .RoleName "assistant"}}{{.Content}}{{else}} [INST] {{if .SystemPrompt}}{{.SystemPrompt}}{{else if eq .RoleName "system"}}<>{{.Content}}<>
> 
> {{else if .Content}}{{.Content}}{{end}} [/INST] {{end}}%
> 
> When i use this model from the text-generation-webui for example, I can see the GPU is being fully utilised. Please let me know what I am doing wrong? Cheers

Sorry, spoke too soon. The indent in the yaml config was wrong. The gpu_layers: 24 shouldn't be under the Parameters, but a standalone option. Now it works with the GPU

**Comment by Aisuko** [comment]
Which example you are using? I do not find the configuration

**Comment by loyaliu** [comment]
You should use llama-cpp (not llama) as backend. This is a example:
```yaml
name: gpt-3.5-turbo
# Default model parameters

parameters:
  # Relative to the models path
  model: mistral-7b-code-16k-qlora.Q4_0.gguf
  # temperature
  temperature: 0.3
  # all the OpenAI request options here..

gpu_layers: 1
f16: true
# Default context size
context_size: 512
threads: 10
# Define a backend (optional). By default it will try to guess the backend the first time the model is interacted with.
backend: llama-cpp
# available: llama, stablelm, gpt2, gptj rwkv

# Enable prompt caching
# prompt_cache_path: "alpaca-cache"
# prompt_cache_all: true

# stopwords (if supported by the backend)
stopwords:
- "HUMAN:"
- "### Response:"
# define chat roles
roles:
  assistant: '### Response:'
  system: '### System Instruction:'
  user: '### Instruction:'
template:
  # template file ".tmpl" with the prompt template to use by default on the endpoint call. Note there is no extension in the files
  completion: xwin-completion
  chat: xwin-chat

```
