### ISSUE TITLE
 v1.40.0-cublas-cuda12 Container won't start

### ISSUE THREAD

**Issue by Roritharr** [mudler/LocalAI#1267]
**LocalAI version:**
quay.io/go-skynet/local-ai:v1.40.0-cublas-cuda12

**Environment, CPU architecture, OS, and Version:**
Docker Desktop, Ryzen 7 5800X3D, Nvidia 3090 FE, Windows 11

**Describe the bug**
Trying to start the docker-compose script ultimately leads to a cmake error:

````
localai-api-1  | -- Found Threads: TRUE
localai-api-1  | -- CMAKE_SYSTEM_PROCESSOR: x86_64
localai-api-1  | -- x86 detected
localai-api-1  | CMake Error at examples/grpc-server/CMakeLists.txt:12 (find_package):
localai-api-1  |   Could not find a package configuration file provided by "absl" with any of
localai-api-1  |   the following names:
localai-api-1  |
localai-api-1  |     abslConfig.cmake
localai-api-1  |     absl-config.cmake
localai-api-1  |
localai-api-1  |   Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
localai-api-1  |   "absl_DIR" to a directory containing one of the above files.  If "absl"
localai-api-1  |   provides a separate development package or SDK, be sure it has been
localai-api-1  |   installed.
localai-api-1  |
localai-api-1  |
localai-api-1  | -- Configuring incomplete, errors occurred!
localai-api-1  | make[1]: *** [Makefile:43: grpc-server] Error 1
localai-api-1  | make[1]: Leaving directory '/build/backend/cpp/llama'
localai-api-1  | make: *** [Makefile:403: backend/cpp/llama/grpc-server] Error 2
localai-api-1 exited with code 0
````

**To Reproduce**
Check out localai, add .env file:

````
## Set number of threads.
## Note: prefer the number of physical cores. Overbooking the CPU degrades performance notably.
THREADS=8

## Specify a different bind address (defaults to ":8080")
# ADDRESS=127.0.0.1:8080

## Default models context size
# CONTEXT_SIZE=512
#
## Define galleries.
## models will to install will be visible in `/models/available`
GALLERIES=[{"name":"model-gallery", "url":"github:go-skynet/model-gallery/index.yaml"}, {"url": "github:go-skynet/model-gallery/huggingface.yaml","name":"huggingface"}]

## CORS settings
# CORS=true
# CORS_ALLOW_ORIGINS=*

## Default path for models
#
MODELS_PATH=/models

## Enable debug mode
# DEBUG=true

## Disables COMPEL (Diffusers)
COMPEL=0

## Enable/Disable single backend (useful if only one GPU is available)
# SINGLE_ACTIVE_BACKEND=true

## Specify a build type. Available: cublas, openblas, clblas.
## cuBLAS: This is a GPU-accelerated version of the complete standard BLAS (Basic Linear Algebra Subprograms) library. It's provided by Nvidia and is part of their CUDA toolkit.
## OpenBLAS: This is an open-source implementation of the BLAS library that aims to provide highly optimized code for various platforms. It includes support for multi-threading and can be compiled to use hardware-specific features for additional performance. OpenBLAS can run on many kinds of hardware, including CPUs from Intel, AMD, and ARM.
## clBLAS:   This is an open-source implementation of the BLAS library that uses OpenCL, a framework for writing programs that execute across heterogeneous platforms consisting of CPUs, GPUs, and other processors. clBLAS is designed to take advantage of the parallel computing power of GPUs but can also run on any hardware that supports OpenCL. This includes hardware from different vendors like Nvidia, AMD, and Intel.
BUILD_TYPE=cuBLAS

## Uncomment and set to true to enable rebuilding from source
REBUILD=true

## Enable go tags, available: stablediffusion, tts
## stablediffusion: image generation with stablediffusion
## tts: enables text-to-speech with go-piper 
## (requires REBUILD=true)
#
GO_TAGS=stablediffusion

## Path where to store generated images
IMAGE_PATH=/tmp

## Specify a default upload limit in MB (whisper)
# UPLOAD_LIMIT

## List of external GRPC backends (note on the container image this variable is already set to use extra backends available in extra/)
# EXTERNAL_GRPC_BACKENDS=my-backend:127.0.0.1:9000,my-backend2:/usr/bin/backend.py

### Advanced settings ###
### Those are not really used by LocalAI, but from components in the stack ###
##
### Preload libraries
# LD_PRELOAD=

### Huggingface cache for models
# HUGGINGFACE_HUB_CACHE=/usr/local/huggingface

### Python backends GRPC max workers
### Default number of workers for GRPC Python backends.
### This actually controls wether a backend can process multiple requests or not.
# PYTHON_GRPC_MAX_WORKERS=1
````

docker-compose.yaml:

````
version: '3.6'

services:
  api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: quay.io/go-skynet/local-ai:v1.40.0-cublas-cuda12
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models
    command: ["/usr/bin/local-ai"]
````

models/stablediffusion.yaml:

````
name: animagine-xl
parameters:
  model: Linaqruf/animagine-xl
backend: diffusers

# Force CPU usage - set to true for GPU
f16: true
diffusers:
  pipeline_type: StableDiffusionXLPipeline
  cuda: true # Enable for GPU usage (CUDA)
  scheduler_type: dpm_2_a
````

**Expected behavior**
The container should have come up and be available to query.

**Logs**

**Additional context**
This was started from Powershell.
