### ISSUE TITLE
Variables available in template file (for prompt)

### ISSUE THREAD

**Issue by netandreus** [mudler/LocalAI#1352]
Can you please tell me, which variables can be used in model template file? Only ```{{.Input}}```?
Do you have some place (like Model Gallery) for usable general prompt templates for supporting models?

**Comment by BackMountainDevil** [comment]
is there any cool geek can show a demo of yaml and teml? I use ggml-gpt4all-j(sha1sum ccfbaf3e2406f442f3b4fefb8672e706aafd522a) and localai docker(v1.40.0 (6ef7ea2635ae5371be4e6eef516c2ad4afd9f4a3)). 

I am not sure things of below are good. so I want a good example

- gpt-3.5-turbo-16k.yaml

```yaml
name: gpt-3.5-turbo-16k-0613
parameters:
  model: ggml-gpt4all-j
  top_k: 80
  temperature: 0.2
  top_p: 0.7
context_size: 8192
stopwords:
- "HUMAN:"
- "GPT:"
roles:
  user: " "
  system: " "
template:
  completion: ggml-gpt4all-j
  chat: ggml-gpt4all-j
```

- ggml-gpt4all-j.tmpl

```tmpl
The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
### Prompt:
{{.Input}}
### Response:

```
