### ISSUE TITLE
Mixtral support ?

### ISSUE THREAD

**Issue by muka** [mudler/LocalAI#1421]
I would like to ask (if not already planned) to support Mixtral from MistralAI 

https://docs.mistral.ai/models/

Thank you

**Comment by lunamidori5** [comment]
Already supported 
@muka https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF

**Comment by muka** [comment]
Awesome! Will check it out, thanks

**Comment by lunamidori5** [comment]
Guess who was wrong... This girl... Hi hello I was confused that was not the model I was thinking about. They seem to have a newer copy of LLama being used @muka / @mudler

**Comment by jamiemoller** [comment]
llamacpp pull req for reference
https://github.com/ggerganov/llama.cpp/pull/4406

**Comment by sweetcard** [comment]
> llamacpp pull req for reference [ggerganov/llama.cpp#4406](https://github.com/ggerganov/llama.cpp/pull/4406)

The pr has been merged. We can update llama.cpp.

**Comment by loversama** [comment]
Could we also get params for: Keys.LLM.EXPERT_COUNT and Keys.LLM.EXPERT_USED_COUNT  in the config when loading?

**Comment by muka** [comment]
> this in our documentation: https://docs.localai.org/en/latest/custom-backends.html#creating-a-custom-backend. If you 

Just to let you know this link points to an unreachable (?) domain .org, instead of .io

**Comment by lunamidori5** [comment]
> > this in our documentation: https://docs.localai.org/en/latest/custom-backends.html#creating-a-custom-backend. If you
> 
> Just to let you know this link points to an unreachable (?) domain .org, instead of .io

Thats a AI, its wrong

**Comment by mudler** [comment]
this PR: https://github.com/mudler/LocalAI/pull/1440 actually updated llama.cpp to point to latest, so master now should work with mixtral

**Comment by Taronyuu** [comment]
Given that this is the only Mixtral related issue in this repository I will share my issues that I ran into here. All thanks to @lunamidori5 who helped me on Discord.

I tried to setup `TheBloke/Mixtral-8x7B-v0.1-GGUF` within LocalAI and went into a complete rabbit hole to setup my chat template which didn't want to work. An hour wasted until Luna recomended to use `TheBloke/dolphin-2.5-mixtral-8x7b-GGUF` instead. This one works with the Luna demo chat template as can be found here: https://localai.io/howtos/easy-model/ After this it worked flawlessly! 

I'll share my config just in case someone needs it in the future, running on an RTX3090.

```
context_size: 4000
name: dolphin-2.5-mixtral-8x7b.Q4_K_M.gguf
parameters:
  model: dolphin-2.5-mixtral-8x7b.Q4_K_M.gguf
  temperature: 0.2
  top_k: 80
  top_p: 0.7
template:
  chat:  chat-block
  chat_message: chat
  completion: completion
backend: llama-cpp
f16: true
gpu_layers: 28
```
Haven't played with any numbers yet other then the `gpu_layers`.
