### ISSUE TITLE
Support for Microsoft Phi-2 model

### ISSUE THREAD

**Issue by fishfree** [mudler/LocalAI#1438]
https://huggingface.co/microsoft/phi-2

**Comment by mudler** [comment]
this should actually just work with current LocalAI: https://huggingface.co/TheBloke/phi-2-GGUF

**Comment by mudler** [comment]
This works here with current master and this YAML config (note GPU settings):

```yaml
context_size: 2048
f16: true
threads: 11
gpu_layers: 90
name: phi-2
mmap: true
parameters:
  model: huggingface://TheBloke/phi-2-GGUF/phi-2.Q8_0.gguf
  temperature: 0.2
  top_k: 40
  top_p: 0.95
template:
  chat: &template |
    Instruct: {{.Input}}
    Output:
  completion: *template
```
