### ISSUE TITLE
Diffusers is not working at all. Load by default stablediffusion instead diffusers

### ISSUE THREAD

**Issue by JZacharie** [mudler/LocalAI#1499]
LocalAI version:
2.2.0-ffmpeg

Environment, CPU architecture, OS, and Version:
Linux srv-gpt 5.15.131-1-pve https://github.com/mudler/LocalAI/issues/1 SMP PVE 5.15.131-2 (2023-11-14T11:32Z) x86_64 x86_64 x86_64 GNU/Linux, Proxmox LXC, AMD Ryzen 9 5900X, 128 GB RAM

Describe the bug
Diffusers is not working at all. Load by default stablediffusion instead diffusers

To Reproduce
I set up dreamlike-photoreal as stated in the docs. File "dreamlike-photoreal.yaml" in models folder with content:

```
name: dreamlike-photoreal
parameters:
  model: Linaqruf/dreamlike-photoreal
backend: diffusers
# Force CPU usage - set to true for GPU
f16: false
diffusers:
  pipeline_type: StableDiffusionPipeline
  cuda: false # Enable for GPU usage (CUDA)
  scheduler_type: euler_a

```
Then ran command as stated in docs:

```
curl http://localhost:8080/v1/images/generations \
    -H "Content-Type: application/json" \
    -d '{
      "prompt": "cat, outdoor, sun, tree|rain, night, people", 
      "model": "dreamlike-photoreal", 
      "step": 51,
      "size": "1024x1024" 
    }'

```
It results always in this error:

Load by default stablediffusion instead diffusers

![image](https://github.com/mudler/LocalAI/assets/6482902/c9cd060c-fe3a-45e1-8c8f-1461abdde2a9)

env with COMPEL=0

/tmp/localai/backend_data/backend-assets/grpc/stablediffusion

![image](https://github.com/mudler/LocalAI/assets/6482902/cd39e187-500e-4356-9622-3f184cb784a6)

![image](https://github.com/mudler/LocalAI/assets/6482902/8f1e99d7-1c0b-4cfa-95c0-dd90b05aa397)

![image](https://github.com/mudler/LocalAI/assets/6482902/da0cba69-0774-4266-bb41-ba56d0b169eb)

Expected behavior
Diffusers generate images.
