### ISSUE TITLE
Chatbot UI does not seems to be working

### ISSUE THREAD

**Issue by ksingh7** [mudler/LocalAI#165]
Hey Guys, love this project and willing to contribute to it.
To learn more about the stuff, i need some help in getting the Chatbot UI to work

Following the example , here is my docker-compose.yaml

```
version: '3.6'

services:

  api:
    image: quay.io/go-skynet/local-ai:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai --threads 8" ]

  web-ui:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    restart: always
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY='
      - 'OPENAI_API_HOST=http://api:8080'
```
- The chatbot UI keeps on loading and throws message unable to find model
![image](https://user-images.githubusercontent.com/9701902/235944311-ba567838-1f10-4358-9339-54b933ac50a0.png)

- I am exposing  Chatbot UI over the internet

Can you pls guide me what should be the value of `OPEN_API_KEY and OPEN_API_HOST` in this case , i am sure something is wrong in my config.

**Comment by ksingh7** [comment]
@mudler helping hand

**Comment by mudler** [comment]
Hey @ksingh7 :wave: 

what do you see in the console? I'd also suggest to set threads with the `.env` file instead of replacing the command in the docker-compose file.

**Comment by swiftugandan** [comment]
The UI is using `http://localhost:3000/api/models` instead of `http://localhost:8080/api/models` ...

**Comment by javea7171** [comment]
Same problem when running locally. Chatbot UI fails to display models

LocalAI:
[127.0.0.1]:43394  200  -  GET      /v1/models
[127.0.0.1]:43400  200  -  GET      /v1/models
[127.0.0.1]:53952  200  -  GET      /v1/models

Chatbot UI: spinner where models selection dropdown should be

**Comment by adamyodinsky** [comment]
Same issue with the endless spinner, can't find models

**Comment by Soberia** [comment]
The spinner will go away if one of the models is named `gpt-3.5-turbo`. However, it's not possible to load more than one model.

**Comment by EchedeyLR** [comment]
I mentioned this at https://github.com/mckaywrigley/chatbot-ui/issues/770

**Comment by PierreMesure** [comment]
I'm also unsuccessful with Chatbot-UI, I added all the `.tmpl` files to make sure the UI detects gpt4all as gpt-3.5-turbo and it shows up when creating a new chat. I can also see that the UI's call to ```https://{{ chat }}/api/models``` is successful.

But trying to talk to the bot returns nothing.

<img width="394" alt="image" src="https://github.com/go-skynet/LocalAI/assets/7223028/a04c2f4d-4581-42ee-be07-6b11e5ca42e8">

The API works.
```
curl https://{{ api }}/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9 
   }'
```

```
{"object":"chat.completion","model":"gpt-3.5-turbo","choices":[{"message":{"role":"assistant","content":"I am doing well. How about you?"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
```

**Comment by akhiljalagam** [comment]
+1

**Comment by karimball** [comment]
Hey there,
you can do a little workaround that issue, but you will have different issues then. Maybe someone have another idea.
I renamed the models/ggml-gpt4all-j  ggml-gpt4all-j.tmpl files to gpt-3.5-turbo  gpt-3.5-turbo.tmpl
Then the Webui is finding the model and you can use the Chat window. But it works not really well. The Model is quite confused and is not responding correctly.

BG

**Comment by hanwsf** [comment]
These files should be availble to make gpt-3.5-turbo models appeal in the model:
completion.tmpl          gpt-3.5-turbo.yaml  
ggml-gpt4all-j           gpt4all.tmpl        

The model is from: wget https://gpt4all.io/models/ggml-gpt4all-j.bin -O models/ggml-gpt4all-j
It works if all files in the models folder.
====
Btw, do you know how to switch to another model in the same models folder? I have rwkv works with curl.

**Comment by hanwsf** [comment]
> Hey Guys, love this project and willing to contribute to it. To learn more about the stuff, i need some help in getting the Chatbot UI to work
> 
> Following the example , here is my docker-compose.yaml
> 
> ```
> version: '3.6'
> 
> services:
> 
>   api:
>     image: quay.io/go-skynet/local-ai:latest
>     restart: always
>     build:
>       context: .
>       dockerfile: Dockerfile.dev
>     ports:
>       - 8080:8080
>     env_file:
>       - .env
>     volumes:
>       - ./models:/models:cached
>     command: ["/usr/bin/local-ai --threads 8" ]
> 
>   web-ui:
>     image: ghcr.io/mckaywrigley/chatbot-ui:main
>     restart: always
>     ports:
>       - 3000:3000
>     environment:
>       - 'OPENAI_API_KEY='
>       - 'OPENAI_API_HOST=http://api:8080'
> ```
> 
> * The chatbot UI keeps on loading and throws message unable to find model
>   ![image](https://user-images.githubusercontent.com/9701902/235944311-ba567838-1f10-4358-9339-54b933ac50a0.png)
> * I am exposing  Chatbot UI over the internet
> 
> Can you pls guide me what should be the value of `OPEN_API_KEY and OPEN_API_HOST` in this case , i am sure something is wrong in my config.

OPEN_API_KEY and OPEN_API_HOST don't need to change if you use local model to inference. OPEN_API_KEY can be anything for local model.

**Comment by iPenx** [comment]
that is because chatbot-ui doesn't define GGML_GPT4ALL_J in the enum OpenAIModelID.

![image](https://github.com/go-skynet/LocalAI/assets/30487681/5583f934-4c8e-4f92-9ace-233bcba29113)

**Comment by nutmilk10** [comment]
> that is because chatbot-ui doesn't define GGML_GPT4ALL_J in the enum OpenAIModelID.
> 
> ![image](https://user-images.githubusercontent.com/30487681/243252983-5583f934-4c8e-4f92-9ace-233bcba29113.png)
> 
> i add these code into chatbot-ui and it worked.
> 
> ![image](https://user-images.githubusercontent.com/30487681/243253237-fdb60dec-7dc7-4dfe-8f7f-224fc81055ea.png)
> 
> ![image](https://user-images.githubusercontent.com/30487681/243253344-af7c5c89-b0b3-473b-814d-cbc2b188a53c.png)

What file is this under, I can't seem to find that line of code in the current repo

**Comment by unifreak** [comment]
> EDIT: I used the new docker-compose provided by @mudler yesterday (thanks! hearts) and it now works! I think the issue was with the files provided in the manual installation or an error on my side when I copied them to my directory.

Can you paste the "docker-compose provided by @mudler"?

**Comment by PierreMesure** [comment]
I added a link in my original message for future reference.

**Comment by fraschm1998** [comment]
Chatbot UI doesn't seem to be using custom models. I have `{"object":"list","data":[{"id":"thebloke__wizardlm-13b-v1-0-uncensored-superhot-8k-ggml__wizardlm-13b-v1.0-superhot-8k.ggmlv3.q4_k_m.bin","object":"model"}]}` which I can query via terminal however chatbot ui does not display available models and tries to use gpt-3.5-turbo.

My docker-compose.yaml:

```
version: '3.6'

services:
  api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: quay.io/go-skynet/local-ai:master-cublas-cuda12
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models
    command: ["/usr/bin/local-ai" ]

  chatgpt:
    depends_on:
      api:
        condition: service_healthy
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://api:8080'
```
