### ISSUE TITLE
document use of api_key / API_KEY

### ISSUE THREAD

**Issue by sbe-arg** [mudler/LocalAI#1869]
I cannot figure out how to set and use API_KEY for nextcloud or http/curl commands

I tried adding the environment var API_KEY='some-value-crypt' in my docker compose

They using it to authenticate in the nextcloud API settings but the same api_key value does not work either on the http enpoint via curl

Does it need any specif requirements or encryption?

```
version: '3.8'

services:

  localai:
    container_name: local-ai
    hostname: local-ai
    image: docker.io/localai/localai:v2.10.1
    ports:
      - 8080:8080
    environment:
      - MODELS_PATH=/models
      - REBUILD=true
      - API_KEY='somevaluehere'
      - BUILD_API_ONLY=false # rebuild everything
      - BUILD_GRPC_FOR_BACKEND_LLAMA=true
      - BUILD_TYPE=openblas
      - GO_TAGS=stablediffusion,tts
      - GALLERIES='[{"name":"model-gallery","url":"github:go-skynet/model-gallery/index.yaml"},{"url":"github:go-skynet/model-gallery/huggingface.yaml","name":"huggingface"}]'
      - THREADS=2
    volumes:
      - localai_models:/models:cached
      - localai_images:/tmp/generated/images/
    command:
      - phi-2
      - tinyllama-chat
      # https://localai.io/basics/getting_started/index.html#running-models
    restart: unless-stopped

volumes:
  localai_models: {}
  localai_images: {}
```

or it needs something on the lines of '["key1","key2"]' or '["{key1"},"{key2}"}' nothing I tried works.

**Comment by chenxinlong** [comment]
For me, the following setting works. Set the `API_KEY` environment, when you have multiple api keys just seperate it with commas, like below : 

```yaml
...
        env:
        - name: DEBUG
          value: "true"
        - name: API_KEY
          value: "aaa,bbb"
...
```

Then send request with Authorization http header with `Bearer ` prefix
```cURL
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Authorization: Bearer aaa' \
--header 'Content-Type: application/json' \
--data '{
     "model": "phi-2",
     "messages": [{"role": "user", "content": "how are you?"}],
     "temperature": 0.3
}'
```
