### ISSUE TITLE
 stderr qemu: uncaught target signal 4 (Illegal instruction) - core dumped

### ISSUE THREAD

**Issue by DavidGOrtega** [mudler/LocalAI#1968]
**LocalAI version:**
docker image latest-aio-cpu I assume [v2.11.0](https://github.com/mudler/LocalAI/releases/tag/v2.11.0)

**Environment, CPU architecture, OS, and Version:**
Macos 13.3.6 M1

**Describe the bug**
Not a single api works. Always throw the error

```
infra-api-1  | 7:26PM DBG GRPC Service Started
infra-api-1  | 7:26PM DBG GRPC(phi-2-chat-127.0.0.1:35789): stderr qemu: uncaught target signal 4 (Illegal instruction) - core dumped
```

**Reproduce**

```yaml
version: "3.9"
services:
  api:
    image: localai/localai:latest-aio-cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
    volumes:
      - ./models:/build/models:cached

```

```sh
docker-compose up
```

**Logs**
In logs I can see also a possible error 

```
2024-04-07 21:15:57 7:15PM INF [/build/backend/python/vall-e-x/run.sh] Fails: grpc process not found: /tmp/localai/backend_data/backend-assets/grpc/build/backend/python/vall-e-x/run.sh. some backends(stablediffusion, tts) require LocalAI compiled with GO_TAGS
```
