### ISSUE TITLE
limit models to api keys

### ISSUE THREAD

**Issue by jtwolfe** [mudler/LocalAI#2046]
**Is your feature request related to a problem? Please describe.**

Capability to limit api key access to models

**Describe the solution you'd like**
configurable yaml file for list of api keys with rate limit (per min) and models assigned for access
potential future extension to external auth tool?
framework for other access controls.
also perhaps a definition for groups? (could be abstracted to external auth but not super useful for small environments :| )

eg
```
users:
 - user:
      api_key: user1_api_key
      limit: 12
      models:
        - model1
        - model2
 - user:
      api_key: user2_api_key
      limit: 8
      models:
        - model3
        - model4
```

**Describe alternatives you've considered**
none, no way to authorize access in this manner

**Additional context**
Its a good feature. Allow multi-user of shared resource deployment and security limits for service accounts.
Useful in dev situations and for integration with common CI to limit overuse due to errors.
I need to gitgudatgo
