### ISSUE TITLE
llama-cpp: object file has no dynamic section

### ISSUE THREAD

**Issue by sozercan** [mudler/LocalAI#3041]
**LocalAI version:**
v2.19.2 and v2.19.3 (v2.19.1 is fine)

**Environment, CPU architecture, OS, and Version:**
Ubuntu 22.04, amd64

**Describe the bug**
Error below:

`DBG GRPC(Meta-Llama-3-8B-Instruct.Q4_K_M.gguf-127.0.0.1:44439): stderr /tmp/localai/backend_data/backend-assets/grpc/llama-cpp-avx2: error while loading shared libraries: /tmp/localai/backend_data/backend-assets/grpc/llama-cpp-avx2: object file has no dynamic section`

**To Reproduce**
`./local-ai --debug --config-file test.yaml`
`curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
    "model": "llama-3-8b-instruct",
    "messages": [{"role": "user", "content": "hello"}]
  }'`

```yaml
- name: llama-3-8b-instruct
  backend: llama
  parameters:
    model: Meta-Llama-3-8B-Instruct.Q4_K_M.gguf
  context_size: 8192
  # cut for brevity
```

**Expected behavior**
Should work as expected, like in v2.19.1

**Logs**
see above

**Additional context**
