### ISSUE TITLE
Coqui voice cloning support

### ISSUE THREAD

**Issue by SlackinJack** [mudler/LocalAI#3347]
**Is your feature request related to a problem? Please describe.**
I would like to use Coqui to clone voices, as it does not have a 15-second output limit like Vall-E-X.

**Describe the solution you'd like**
Voice cloning in Coqui can be achieved using the following patch (in Coqui backend.py):
```
if self.tts.is_multi_speaker and self.AudioPath is not None:
    self.tts.tts_to_file(text=request.text, speaker_wav=self.AudioPath, language=lang, file_path=request.dst)
else:
    self.tts.tts_to_file(text=request.text, speaker=request.voice, language=lang, file_path=request.dst)
# ORIGINAL:
#if self.tts.is_multi_speaker and request.voice is not None:
#    self.tts.tts_to_file(text=request.text, speaker=request.voice, language=lang, file_path=request.dst)
#else:
#    self.tts.tts_to_file(text=request.text, speaker_wav=self.AudioPath, language=lang, file_path=request.dst)
```

And with a model using the following parameters:
```
name: cloned-voice-coqui
backend: coqui
parameters:
  language: en
  model: tts_models/multilingual/multi-dataset/xtts_v2
tts:
  vall-e:
    audio_path: /absolute/path/to/voice_sample.wav
```

**Additional context**
The above patch has been tested to work on my system, however it would be misleading to use the key "tts/vall-e/audio_path" for audio_path since we are not using Vall-E.
