### ISSUE TITLE
feature: identify model file by SHA

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#36]
If the API would support model aliases that would allow to plug into existing webui more easily, without supporting directly each one of them. Seems all the UI out there filter by known models - even if the api returns the supported models

**Comment by mudler** [comment]
maybe we can pass the model via the token? However, won't spare from UI filtering what /models actually returns.

**Comment by mudler** [comment]
A config file, could be:

```yaml
-  model: my-cerebras
   file: cerebras.bin
   top_p: ..
   temperature: ...
   stop_words:
   - 
   alias: 
   - gpt4
   template:
       completion: file.tmpl
       chat: file.tmpl
```

**Comment by mkellerman** [comment]
Another example:
```
models:
  - name: ggml-gpt4all-j
    checksum:
      - sha256: ...
    path: /models/ggml-gpt4all-j.bin
    backend: gpt4all-j
    defaults:
      top_p: ...
      stop_words: ...
      prompts:
        - completion: ...
        - chat: ...
    aliases:
      - gpt-3.5-turbo
      - gpt4

  - name: cerebras-2.7b-q4_0
    checksum:
      - sha256: ...
    path: /models/cerebras-2.7b-q4_0.bin
    backend: gpt2
    defaults:
      top_p: ...
      stop_words: ...
      prompts:
        - completion: ...
        - chat: ...
    aliases:
      - gpt2
```

You could even point to the same model sha/path, and give it a different name and use different prompts. this allows the maximum of flexibility per users needs.

**Comment by normen** [comment]
As talked about on Discord, my proposition is this below.

It takes into consideration:
- Separating models from configurations 
  - use one model for multiple things
  - or different models on different paths / model names
- Considering the fact that we emulate the OpenAI API and have limited info at the server endpoint
  - only "model" and API path is known

Folder structure:
```
│
├─models
│ │
│ └─mymodel.bin
│
└─configs
  │
  ├─generic_completion.yaml
  │
  └─stableml.yaml

```

Content of one config yaml:
```yaml
name: generic_completion
shas:
  - 81237981273
  - 1283128937
paths:
  - v1/chat
  - v1/completion
model_names:
  - gpt-3.5-turbo
  - gpt-4
backend: gpt4all-j
top_p: ...
stop_words:
  - <|USER|>
  - <|SYSTEM|>
completion_prompt: Complete the following text.
chat_prompt: This is the discussion of an AI and a Human...
chat_system: <|SYSTEM|>
chat_user: <|USER|>
chat_assistant: <|ASSISTANT|>
```

**How it works**
When a request comes in:
- Model name and API path is known
- Configs are scanned for combination of path and name
- If the combination is found, the list of sha's is checked
- We look for a fitting model in memory or disk
- We apply the config and run the inference
- Ofc all this should be buffered

**User Side**
- There could be default config files with known-to-work shas.
  - These would auto-configure any known bin files in the models folder
- If a user-created config.yaml file overrides a path/name/sha combination it is used instead.

The user can for example..
- Copy a default config.yaml and adapt it for their needs
- Change the prompt or use a different model (add a sha)
- Add a different model name so the configuration can be used via the OpenAI API request
