### ISSUE TITLE
Issues with running Local AI CPU version in Docker – Model loading errors

### ISSUE THREAD

**Issue by vawaver** [mudler/LocalAI#3747]
Hello,

I'm encountering issues while trying to set up the Local AI CPU version in a Docker container on my Ubuntu Server 24.04. I've been following the official documentation and Apfelcast's guide, but I'm unable to get the Chat feature to work. The WebUI starts without any issues, but the models fail to load, and the Chat doesn't respond.

Here are some key details from the logs:

```
Fails: could not load model: rpc error: code = Unavailable desc = error reading from server: EOF
```

It seems that the models, which are stored in the `models/` directory (in `.gguf` format), cannot be properly loaded. I've also noticed the following gRPC-related errors:

```
connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:<port>: connect: connection refused"
```

I've tried running Docker as `root` and adjusting the ownership of the model files (currently owned by `root:root`), but these steps didn't help. Additionally, I increased the gRPC attempts and delay, but the issue persists.

Here’s my `docker-compose.yml` for reference:

```yaml
services:
  api:
    image: localai/localai:latest-aio-cpu
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
    volumes:
      - ./models:/build/models:cached
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    restart: unless-stopped
```

I'm attaching the log file for more context. I would really appreciate any guidance or suggestions on what might be going wrong. Has anyone else experienced similar issues with model loading or gRPC communication in the CPU version? Any tips or advice would be incredibly helpful!

[_localai-api-1_logs01.txt](https://github.com/user-attachments/files/17282545/_localai-api-1_logs01.txt)
