### ISSUE TITLE
Here's a working config for nVidia Nemotron Mini 4B Instruct

### ISSUE THREAD

**Issue by superjamie** [mudler/LocalAI#4234]
Nemotron is a model by nVidia with a template format I had not seen before:

- https://huggingface.co/nvidia/Nemotron-Mini-4B-Instruct
- https://huggingface.co/bartowski/Nemotron-Mini-4B-Instruct-GGUF

Here is a tested working config file:

```yaml
context_size: 4096
f16: true
mmap: true
name: Nemotron-Mini-4B-Instruct
parameters:
  model: bartowski/Nemotron-Mini-4B-Instruct-GGUF/Nemotron-Mini-4B-Instruct-Q8_0.gguf
stopwords:
- </s>
template:
  chat: |
    <extra_id_1>User
    {{.Input}}
    <extra_id_1>Assistant
    
  chat_message: |
    {{if eq .RoleName "assistant"}}<extra_id_1>Assistant{{else if eq .RoleName "system"}}<extra_id_0>System{{else if eq .RoleName "user"}}<extra_id_1>User{{end}}
    {{.Content}}
  completion: |
    {{.Input}}
```

I did not do Tool usage because I do not use it.
