### ISSUE TITLE
[2.25.0] Model gallery is empty + Error 500 since upgrade to 2.25.0

### ISSUE THREAD

**Issue by yscialom** [mudler/LocalAI#4617]
**LocalAI version:**

LocalAI Version v2.25.0 (07655c0c2e0e5fe2bca86339a12237b69d258636)
Docker image: localai/localai:latest-aio-gpu-nvidia-cuda-12 1b02a558e76d

**Environment, CPU architecture, OS, and Version:**

* Linux Ubuntu 24.10
* CPU: Ryzen 9 5900X
* GPU: NVIDIA GeForce RTX 3060
* Docker: Server Version: 26.1.3

**Describe the bug**

Since I've upgraded to version 2.25, the list of available models is empty on `/browse` and `/models/available` raises a HTTP 500 error.

**To Reproduce**

1. Create file `docker-compose.yaml`:
```yaml
services:
  api:
    image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      DEBUG: true
    volumes:
      - .localai//models:/build/models:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
2. Start the container with `docker compose up -d`
3. Query the list of models with `curl -XGET 'http://localhost:8080/models/available' -H 'accept: application/json'`
4. With your favourite web browser, open url `http://localhost:8080/browse`.

**Expected behaviour**

Both list all models from `https://github.com/mudler/LocalAI/tree/master/gallery`.

**Observed behaviour**

1. `curl -XGET 'http://localhost:8080/models/available' -H 'accept: application/json'` raises an error 500:
```json
{"error":{"code":500,"message":"yaml: map merge requires map or sequence of maps as the value","type":""}}
```

2. `/browser` is empty:

![Image](https://github.com/user-attachments/assets/c47c75e3-4f15-4363-935e-f4d1be68dc68)

**Logs**

```
api-1    | 8:01PM DBG Listing models from galleries: [{URL:github:mudler/LocalAI/gallery/index.yaml@master Name:localai}]
api-1    | 8:01PM ERR Server error error="yaml: map merge requires map or sequence of maps as the value" ip=172.19.0.1 latency=45.078905ms method=GET status=500 url=/models/available
api-1    | 8:02PM INF Success ip=172.19.0.1 latency=46.570036ms method=GET status=200 url=/browse/
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="26.651µs" method=GET status=200 url=/static/assets/highlightjs.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="34.434µs" method=GET status=200 url=/static/assets/highlightjs.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="39.835µs" method=GET status=200 url=/static/assets/alpine.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="8.977µs" method=GET status=200 url=/static/assets/marked.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="21.23µs" method=GET status=200 url=/static/assets/purify.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="7.975µs" method=GET status=200 url=/static/general.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="11.211µs" method=GET status=200 url=/static/assets/font1.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="8.166µs" method=GET status=200 url=/static/assets/font2.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="12.794µs" method=GET status=200 url=/static/assets/tw-elements.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="7.604µs" method=GET status=200 url=/static/assets/tailwindcss.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="9.408µs" method=GET status=200 url=/static/assets/fontawesome/css/fontawesome.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="5.47µs" method=GET status=200 url=/static/assets/fontawesome/css/brands.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="8.205µs" method=GET status=200 url=/static/assets/fontawesome/css/solid.css
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="4.449µs" method=GET status=200 url=/static/assets/flowbite.min.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="4.87µs" method=GET status=200 url=/static/assets/htmx.js
api-1    | 8:02PM INF Success ip=172.19.0.1 latency="5.03µs" method=GET status=200 url=/static/assets/tw-elements.js
```
