### ISSUE TITLE
deepseek-r1-distill-qwen-7b (and seemingly other reasoning models) exclude initial <think> tag

### ISSUE THREAD

**Issue by RealJohnGalt** [mudler/LocalAI#4761]
**LocalAI version:**
464686aee65e31924d282e71a037d857b8d0504e

**Environment, CPU architecture, OS, and Version:**
linux + vulkan

**Describe the bug**
I am excluding the proper think tags since I cannot get them to show due to markdown.
deepseek-r1-distill-qwen-7b (and other deepseek models I've tested) exclude the initial think tag, but include the "/think" tag after. This is creates an issue with some frontends such as open webui, since they recently added support for think tags and hiding/showing/giving stats on thinking.

**To Reproduce**
Ask any question, response begins with reasoning directly, and ends with /think but has no beginning think tag.

**Expected behavior**
I expect think to precede the thinking.

An example output from: why is the sky blue?

> 
> Okay, the user is asking, "why is the sky blue?" I remember that there are a few explanations for this, so I need to figure out which one is the most accurate based on the provided context. 
> 
> Looking at the context, there are two sources with the same question. Both sources explain that the sky appears blue because of the scattering of sunlight by atmospheric molecules. When sunlight enters the Earth's atmosphere, it's made up of all the colors of the spectrum. As it travels through the air, shorter wavelengths like blue and violet are scattered more than the longer wavelengths like red and orange. This scattering makes the sky appear blue, especially when the sun is high in the sky. 
> 
> The context also mentions that in polluted skies, small particles like dust can scatter more blue light, making the sky look more blue. However, the user's question is general, so I don't need to include that unless it's necessary. Also, I should cite the sources that provide this information. Since both sources are from Britannica, I'll use [britannica.com] for the context. 
> 
> I should structure my answer to first explain the phenomenon, then mention the factors that contribute to the sky's color. I'll include the citation at the end to give credit to the source. I'll keep it concise and clear, making sure it addresses the user's question directly.
> </think> 
> 
> The sky appears blue primarily due to the scattering of sunlight by molecules in the Earth's atmosphere. Sunlight is composed of all the colors of the visible spectrum, but shorter wavelengths like blue and violet are scattered more than longer wavelengths like red and orange. This scattering effect is more pronounced when the sun is high in the sky, as the sunlight travels through a larger portion of the atmosphere. The result is that the sky appears blue to our eyes [britannica.com].

**Comment by RealJohnGalt** [comment]
Removed with markdown, but the end of the second paragraph had the /think tag without any initial think tag used

**Comment by RealJohnGalt** [comment]
Since this affects all thinking models, I've attempted to force `<think>` to the beginning of responses in yaml, but my attempts are either incorrect or something else is stripping out the initial `<think>`

**Comment by TheDarkTrumpet** [comment]
You can fix this fairly easily, it doesn't really need a ticket.

Step 1 - create a new template file, call it something like: `chatml-thinking-block.tmpl`, and inside it include the following:

```
{{.Input}}
<|im_start|>assistant
<think>
```

Then, inside your yaml file for the gguf, mine is `DeepSeek-R1-Distill-Qwen-32B-abliterated-Q5_K_M.yaml` you can have the following:

```yaml
context_size: 65536
f16: true
threads: 4
gpu_layers: 90
name: DeepSeek R1 Distill Qwen 32B
tensor_split: "90,0,0"
main_gpu: "0"
prompt_cache_all: false
parameters:
  model: DeepSeek-R1-Distill-Qwen-32B-abliterated-Q5_K_M.gguf
  temperature: 0.7
  top_k: 40
  top_p: 0.95
  batch: 512
  tfz: 1.0
  n_keep: 0
#  rope_freq_base: 4000000
template:
  chat_messages: chatml
  chat: chatml-thinking-block
  completion: completion
stopwords:
- <|im_end|>
- <|end▁of▁sentence|>
- <｜end▁of▁sentence｜>
```
